### PR TITLE
Add a test to demonstrate issue with django 1.11

### PR DESCRIPTION
**Pull request by ticosax**
If model with state field has other fields that access their field value
via a property or a Virtal Field, then creation of instances will fail.

I do not know yet how to fix it but I will work on it.

### CODE REVIEW

**Comment by dtatarkin** [comment]
I think this https://github.com/kmmbvnr/django-fsm/pull/173 will solve problem.

**Comment by ticosax** [comment]
Thank you @dtatarkin. I cherry-picked your fix in the pull request.

**Comment by karyon** [comment]
i had the same issue and can confirm that the fix actually fixes it, i'm now using this branch in my project. @kmmbvnr a merge would be greatly appreciated :)

**Comment by AmbientLighter** [comment]
This fix is blocker for Django 1.11 support. @kmmbvnr could you please accept it?

**Pull request merged**
